### ISSUE TITLE
Flashing Returned

### ISSUE THREAD

**Issue by wisecameron** [bkhpanigha/hh-suttas#194] opened 2024-10-26 03:10 UTC
@Reptilioo Hey I saw you removed the "appbody hidden" class - just wanted to point out that it caused the flashing to return when the site loads.  If we don't mind it, we might as well remove the finally block from the js since now it's just extraneous.  Otherwise I can bring it back.  

If we don't want the flickering, I'll also figure out how to fix the "foreword" flashing.

**Comment by wisecameron** [comment] 2024-10-26 03:11
Also my bad with offline mode :(

**Comment by Reptilioo** [comment] 2024-10-26 07:23
@wisecameron hey, my bad I didn't do it on purpose but just didn't see you
added that and overwrote it with previous code slightly modified.
No problems the issue caused by the refactoring is minor, just a 'success'
message not showing

Le sam. 26 oct. 2024 à 05:11, Cameron Warnick ***@***.***> a
écrit :

**Comment by bkhpanigha** [comment] 2024-10-26 11:14
@Reptilioo @wisecameron In case it helps, Firefox console says the following: "Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content."

**Comment by Reptilioo** [comment] 2024-10-26 15:21
@wisecameron @bkhpanigha .appbody was added back, do you still experience flashing?

**Comment by wisecameron** [comment] 2024-10-26 16:41
> @wisecameron @bkhpanigha `.appbody` was added back on `<body>`, do you still experience flashing?

Totally fixed!  Glad it still works with the new changes.  And totally no big deal, I'm not possessive over code AT ALL (from my experience, people who are like that make everybody walk on eggshells, for nothing).   Plus it would be functionally impossible to have taken note of the totality of those changes haha.

**Comment by wisecameron** [comment] 2024-10-26 16:42
![image](https://github.com/user-attachments/assets/d983488a-4093-4591-96bc-59f24eef8da5)

Haven't been able to get it to run locally for a few days, is it working for everybody else?  It's running great on live so I'm guessing it's a me-problem.

**Comment by Reptilioo** [comment] 2024-10-26 18:01
@wisecameron see #199. 
It's an issue I implemented with #192 and that is fixed with PR #203.

**Comment by Reptilioo** [comment] 2024-10-26 18:14
We can close this one.

**Comment by wisecameron** [comment] 2024-10-26 18:37
Gotcha, nice work ^

**Closed** 2024-10-27 12:54 UTC
